authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
     path('', views.login_page, name='login'),
     path('logout/', views.logout, name='logout'),
     path('signup/', views.signup, name='signup'),
     
    

]

directInsurance/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

from xml.etree.ElementInclude import include
from django.urls import path, re_path,  include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentification/', include('authentification.urls', namespace='authentification')),
    path('données/', include('données.urls', namespace='données')),


    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

données/urls.py
from django.urls import path
from . import views

app_name = 'données'

urlpatterns = [
    path('', views.index, name='index'),
    path('rapport/', views.rapport, name='rapport'),
    path('getRapport/', views.getRapport, name='getRapport'),
    path('client/', views.client, name='client'),

     

]

authentification/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Utilisateur(AbstractUser):

    choices = (
    (0, 'DGA'),
    (1, 'Secretaire'),
    (2, 'Caissière'),
    (3, 'Productrice'),
    (4, 'Informaticienne')
    )
    code = models.CharField(max_length=5, null=False)
    poste = models.IntegerField(default=0, choices=choices )
    tel = models.CharField(default=0, max_length=20)

    def __str__(self):
        return self.username 

données/models.py
from django.db import models
from authentification.models import Utilisateur




# Create your models here.





class Client(models.Model):


    choices = (
    ('auto', 'Auto'),
    ('voyage', 'voyage'),
    ('Maladie', 'Maladie'),
    ('Tout risque', 'Tout risque'),
    ('Caution', 'Caution'),
    )
    nom = models.CharField(max_length=200, null=False)
    prenom = models.CharField(max_length=200, null=False)
    adresse = models.CharField(max_length=200, null=False)
    email = models.CharField(max_length=200, null=False, )
    date_naiss = models.DateField()
    tel = models.CharField(default=0, max_length=200)
    typeAssur = models.CharField(null= False, max_length=200, choices=choices )
    autre = models.TextField(null=True)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)

    def __str__(self):
        return f'{self.nom} {self.id}'   

class Presence(models.Model):
    jour_fiche = models.DateTimeField()
    heure_arri = models.DateTimeField()              
    heure_dep = models.DateTimeField()              
    deb_pause = models.DateTimeField()              
    fin_pause = models.DateTimeField()
    utilisateur = models.ForeignKey(Utilisateur, on_delete = models.CASCADE, default=0) 
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)


    class Meta:
        ordering=('-created_at',)

    def __str__(self):
        return f'{self.jour_fiche} {self.id}'   

class Rapport(models.Model):
    date = models.DateTimeField()
    libelle = models.TextField(max_length=200, null=False)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at =models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('-created_at',)

    def __str__(self):
        return f'{self.date} {self.id}' 

authentification/forms.py
# authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    choices = (
    (0, 'DGA'),
    (1, 'Secretaire'),
    (2, 'Caissière'),
    (3, 'Productrice'),
    (4, 'Informaticienne')
    )
    username = forms.CharField(max_length=63, label='Nom d’utilisateur ')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Mot de passe ')
   


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')    

données/forms.py
from django.forms import ModelForm, Textarea, DateTimeInput
from . import models
from .models import Rapport, Client
from django import forms


class RapportForm(ModelForm):
    class Meta:
        model = Rapport
        fields = ('date', 'libelle',)  
        widgets = {

            'lebelle': Textarea(attrs={'cols':50,'rows':10}),
            'date': DateTimeInput(),
        }


class ClientForm(forms.Form):

    # class Meta:
    #     model = Client
    #     fields = ('nom','adresse','email', 'date_naiss', 'tel', "typeAssur", 'autre')

    choices = (
    ('auto', 'Auto'),
    ('voyage', 'voyage'),
    ('Maladie', 'Maladie'),
    ('Tout risque', 'Tout risque'),
    ('Caution', 'Caution'),
    )

    nom = forms.CharField(max_length=200,label='Nom/Raison Social' )
    # prenom = forms.CharField(max_length=200,label='Nom/Raison Social')
    adresse = forms.CharField(max_length=200, label='adresse')
    email = forms.EmailField(max_length=200,label='Email')
    date_naiss = forms.DateField(label='Date de Naissance')
    tel = forms.CharField( max_length=200, label='Téléphone')
    typeAssur = forms.ChoiceField(choices=choices, label='Type Assurance' )
    autre = forms.CharField(widget=forms.Textarea(attrs={'cols':30,'rows':5})) 
          

authentification/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model, login

from . import forms

# # Create your views here.

User = get_user_model()
def login_page(request, *args, **kwargs):
    form = forms.LoginForm()
    message = ''
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                
            )
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                message = 'Identifiants invalides.'
    return render(
        request, 'authentification/login.html', context={'form': form, 'message': message})    
     
                  
def logout_user(request):
    logout(request)
    return redirect(login)

# def index(request, *args, **kwargs):
#     users = Utilisateur.objects.all()

#     context = {
#         'users' : users
#     }

#     return render(request, 'authentification/index.html')






User = get_user_model()

def signup(request, *args, **kwargs):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        mail = request.POST.get('mail')
        poste = request.POST.get('poste')
        tel = request.POST.get('tel')
         
        user = User.objects.create_user(username = username, password = password) 
        login(request, user)
        return redirect('login')
    return render(request, 'authentification/signup.html')

données/views.py
from django.shortcuts import render, redirect
from authentification.models import Utilisateur
from .forms import RapportForm, ClientForm
from .models import Rapport, Client
from . import models  
from django import forms

    
def index(request, *args, **kwargs):
    users = Utilisateur.objects.all()

    context = {
        'users' : users
    }

    return render(request, 'données/index.html', context)


def rapport(request, *args, **kwargs):
    
    form = RapportForm()
    if request.method =="POST":
        form = RapportForm(request.POST)
        if form.is_valid():
            form.save()
    
    return render(request, 'données/rapport.html', {'form':form}) 




def getRapport(request, *args, **kwargs):
    rapports = Rapport.objects.all()
    # context['rapport'] = rapport


    print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<')
    print(request.rapport.date)
    print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<')

    return render(request, 'données/rapport.html', {'rapports' : rapports})


def client(request, *args, **kwargs):
    
    form = ClientForm()
    if request.method =="POST":
        form = ClientForm(request.POST)
        if form.is_valid():
           form.save()    
    return render(request, 'données/client.html', {'form':form})  


# def client(request, *args, **kwargs):
#     nom = request.POST.get('username'),
#     adresse = request.POST.get('adresse'),
#     mail = request.POST.get('mail'),
#     date_naiss = request.POST.get('date_naiss'),
#     tel = request.POST.get('tel'),
#     typeAssur = request.POST.get('type'),
#     autre = request.POST.get('autre'),
#     client = Client(nom=nom, adresse=adresse, email=mail, date_naiss=date_naiss, 
#     tel=tel, typeAssur=typeAssur, autre=autre)
          

#     client.save()    
#     return render(request, 'données/client.html', {'client':client})  




# def signup(request, *args, **kwargs):

#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('pwd')
#         mail = request.POST.get('mail')
#         poste = request.POST.get('poste')
#         tel = request.POST.get('tel')
         
#         user = User.objects.create_user(username = username, password = password) 
#         login(request, user)
#         return redirect('login')
#     return render(request, 'authentification/signup.html')       

données/templates/données/authentification.html
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=!, initial-scale=1.0">
    <link rel="stylesheet" href="authentification.css">

    <title>test</title>
</head>

<body>


    <form action="/authentification" method="post">
        <div class="form">
            <h2>Connexion</h2>
            <div class="inputBox">
                <label class="nom">username</label>
                <input type="text" name="username" id="username">
                <small></small>
    
            </div>
            <div class="inputBox">
                <label class=password>Password</label>
                <input type="text" name="pwd" id="pwd">
                <small></small>
    
            </div>
    
            <div class="inputBox">
                <label class="nom">Adresse Mail</label>
                <input type="email" name="mail" id="mail">
                <small></small>
    
            </div>
            <div class="bouton">
             <button type="submit"><a href="{% url 'données:index' %}"></a>Se connecter</button> 
    
            </div>
            <div>
                <label for="fogot" style="margin: 10px;">Mot de passe oublié?</label>
                <a href="{% url 'données:creation' %}">Cliquer ici</a>
            </div>
        </div>
    </form>

    
</body>


</html> -->



<!-- # authentication/templates/authentication/login.html -->

données/templates/données/client.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=!, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/presence.css' %}">

    <title>test</title>
</head>

<body>

    <form action="" method="POST" enctype="multipart/form-data"> 
        {% csrf_token %}

       

    <div class="forme">
        <h2>Création client</h2>
        {{ form.as_p }}
        <!-- <div class="inputBox">
            <label class="nom">Nom/Raison sociale</label>
            <input type="text" name="username" id="username">
            <small></small>

        </div> -->
        <!-- <div class="inputBox">
            <label class=password>Prénom</label>
            <input type="text" name="prenom" id="prenom">
            <small></small>

        </div> -->

        <!-- <div class="inputBox">
            <label class="nom">Adresse</label>
            <input type="adresse" name="adresse" id="adresse">
            <small></small>

        </div>

        <div class="inputBox">
            <label class="nom">Adresse</label>
            <input type="email" name="mail" id="mail">
            <small></small>

        </div>

        <div class="inputBox">
            <label class="date">Date Naissance</label>
            <input type="date" name="date_naiss" id="date_naiss">
            <small></small>

        </div>

        <div class="inputBox">
            <label class="tel">Téléphone</label>
            <input type="number" name="tel" id="tel">
            <small></small>

        </div>

        <div class="selection">
            <label for="poste">Type d'assurance : </label>
            <input type="checkbox" name="type" id="">
            <label for="">Auto</label>
            <input type="checkbox" name="type" id="">
            <label for="">Maladie</label><br><br>
            <input type="checkbox" name="type" id="">
            <label for="">Voyage</label>
            <input type="checkbox" name="" id="">
            <label for="">Caution</label>
            <input type="checkbox" name="" id="">
            <label for="">Responsabilité</label><br><br>
             
            <label for="">Autre type d'assurance : </label>
            <textarea name="autre" id="autre" cols="50" rows="3"></textarea>
        </div>     -->

        
        <div class="bouton">
        <button type="submit"><a href="{% url 'données:rapport' %}" style="color: white; text-decoration: none; font-size: 20px;">Valider</a></button>
        <button onclick="secretaire.html">Annuler
        </button>

        </div>
        
    </div>

</form>
</body>


</html>

données/templates/données/creation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=!, initial-scale=1.0">
    <link rel="stylesheet" href="authentification.css">

    <title>test</title>
</head>

<body>
    <form method="POST" action="/creation">
        {% csrf_token %}

        <div class="form">
            <h2>authentification</h2>
            <div class="inputBox">
                <label class="nom">username</label>
                <input type="text" name="username" id="username">
                <small></small>
    
            </div>
            <div class="inputBox">
                <label class=password>Password</label>
                <input type="text" name="pwd" id="pwd">
                <small></small>
    
            </div>
    
            <div class="inputBox">
                <label class="nom">Adresse Mail</label>
                <input type="email" name="mail" id="mail">
                <small></small>
    
            </div>
    
            <div class="selection">
                <label for="poste">Poste occupé(e) : </label>
                <select name="posteoccup" id="">
                    <option value="secret">Secrétaire</option>
                    <option value="secret">Productrice</option>
                    <option value="secret">Commerciel(e)</option>
                </select>
            </div>
            <div class="bouton">
            <button type="submit"><a href="/authentification.html">Valider</a></button>
            <!-- <button type="submit"><a href="/singup">Annuler</a></button> -->
            <button onclick="secretaire.html">Annuler
            </button>
    
            </div>
            
        </div>
    </form>
    
</body>


</html>

données/templates/données/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=!, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/presence.css' %}">
    <title>secretaire</title>
</head>
<body>
    <div class="alle">
        <div>
            <h1>Direct<span>Insurance</span></h1>
        </div>
        <div class="liens">
            <a href="secretaire.html">Fiche Présence</a>
            <a href="{% url 'données:rapport' %}">Rapport</a>
        </div>
        <button >
            <a href="{% url 'authentification:login' %}" style="font-size: 15px; text-align: center; color: white;">Se Deconnecter</a></button>
    </div>

    <div>
       <div class="corps">
         <h1>fiche de présence</h1>
         <label for="fiche">Fiche de présence au :</label>
         <input type="date" name="date" id="">
       </div>
         <table>
            <div >
                <th>
                    <tr class="teteA">
                        
                        <td>Nom</td>
                        <td colspan="2">Présence</td>
                        <!-- <td>Pause</td> -->
                        <td colspan="2">Pause</td>
                    </tr>

                </th>
               <div>
                <tr class="teteB">
                    <td></td>
                    <td>Arrivé(e)</td>
                    <td>Départ</td>
                    <td>Départ</td>
                    <td>Départ</td>
                </tr>
               </div>
                
            </div>

            <div>
                <tr class="tetec">
                    <td>{{ Utilisateur.username }}</td>
                    <td><input type="time" name="" id=""></td>
                    <td><input type="time" name="" id=""></td>
                    <td><input type="time" name="" id=""></td>
                    <td><input type="time" name="" id=""></td>
                </tr>
               </div>
         </table>
       </div>
    </div>
</body>
</html>

données/templates/données/rapport.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=!, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/rapport.css' %}">
    <title>rapport</title>
</head>
<body>
    
    
   <div>
    <div class="alle">
        <div>
            <h1>Direct<span>Insurance</span></h1>
        </div>
        <div class="liens">
            <a href="secretaire.html">Fiche Présence</a>
            <a href="rapport.html">Rapport</a>
        </div>
        <button>Se Deconnecté</button>
    </div>
    <div class="corps">
        <h1>Rapport journalier</h1>
        <input type="search" name="recherche" id="" placeholder="Rechercher....">
        <div class="plus">
            <h2>Historique des rapport</h2>
            <div>
            <button onclick="boite()">+</button>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
            <diolog>
                <div id="boite">
                    <div>
                        
                        <p for="date">{{ rapport.date }}</p>
                        <p for="motif">Ajouter le nimi rapport</p>
                        {{ form.as_p }}
                        <!-- <textarea name="text" id="libelle" name="libelle" cols="50" rows="10"></textarea> -->
                        <button type="submit" ><a href="{% url 'données:rapport' %}" style="color: white; text-decoration: none; font-size: 20px;">Ajouter le mini rapport</a></button>
                        <!-- <button onclick="soumettre(event)">Annuler le mini rapport</button> -->
                    </div>
                </div>
            </diolog>
        </form> 
            </div>
        </div>
        {% for rapport in rapports %}
        <div class="contenu">
            <label for="jour">{{ rapport.date }} : </label>
            <label for="jour">{{ rapport.libelle }}</label>
        </div>
        {% endfor %}
        <div class="contenu">
            <label for="jour">12/02/2023 : </label>
            <label for="jour">monsieur est venu vous chercher et il a demande une cotation de....</label>
        </div>

    </div>
   </div> 


   <script>
    function boite(event){
        reservation = document.getElementById("boite");
        reservation.style.visibility = reservation.style.visibility =="visible" ? "hidden" : "visible"
    
    }

    function soumettre(event){
    let selection = document.querySelector("#selection")
    let nombre = document.querySelector("#nombre")
    if(nombre.value == ""|| nombre.value<=0){
        alert("entrer un nombre positif")
    }

    reservation = document.getElementById("boite");
        reservation.style.visibility = reservation.style.visibility =="visible" ? "hidden" : "visible"
    }
    </script>
   
</body>
</html>