authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
     path('', views.login_page, name='login'),
     path('logout/', views.logout, name='logout'),
     path('signup/', views.signup, name='signup'),
     
    

]

directInsurance/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

from xml.etree.ElementInclude import include
from django.urls import path, re_path,  include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentification/', include('authentification.urls', namespace='authentification')),
    path('données/', include('données.urls', namespace='données')),


    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

données/urls.py
from django.urls import path
from . import views

app_name = 'données'

urlpatterns = [
    path('', views.index, name='index'),
    path('rapport/', views.rapport, name='rapport'),
    path('getRapport/', views.getRapport, name='getRapport'),
    path('client/', views.client, name='client'),

     

]

authentification/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class Utilisateur(AbstractUser):

    choices = (
    (0, 'DGA'),
    (1, 'Secretaire'),
    (2, 'Caissière'),
    (3, 'Productrice'),
    (4, 'Informaticienne')
    )
    code = models.CharField(max_length=5, null=False)
    poste = models.IntegerField(default=0, choices=choices )
    tel = models.CharField(default=0, max_length=20)

    def __str__(self):
        return self.username 

authentification/forms.py
# authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    choices = (
    (0, 'DGA'),
    (1, 'Secretaire'),
    (2, 'Caissière'),
    (3, 'Productrice'),
    (4, 'Informaticienne')
    )
    username = forms.CharField(max_length=63, label='Nom d’utilisateur ')
    password = forms.CharField(max_length=63, widget=forms.PasswordInput, label='Mot de passe ')
   


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')    

authentification/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model, login

from . import forms

# # Create your views here.

User = get_user_model()
def login_page(request, *args, **kwargs):
    form = forms.LoginForm()
    message = ''
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                
            )
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                message = 'Identifiants invalides.'
    return render(
        request, 'authentification/login.html', context={'form': form, 'message': message})    
     
                  
def logout_user(request):
    logout(request)
    return redirect(login)

# def index(request, *args, **kwargs):
#     users = Utilisateur.objects.all()

#     context = {
#         'users' : users
#     }

#     return render(request, 'authentification/index.html')






User = get_user_model()

def signup(request, *args, **kwargs):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        mail = request.POST.get('mail')
        poste = request.POST.get('poste')
        tel = request.POST.get('tel')
         
        user = User.objects.create_user(username = username, password = password) 
        login(request, user)
        return redirect('login')
    return render(request, 'authentification/signup.html')

authentification/templates/authentification/login.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static '/authentification/css/inscription.css' %}">
        <title>authentification</title>
    </head>
    <body>
        <div class="form">
            <h2>Authentification</h2>
            <p>{{ message }}</p>
            <form method="post">
                <div class="inputBox">
                    {{ form.as_p }}
                    {% csrf_token %}

                </div>
              
                <button type="submit" style="align-items: center; margin-left: 50px ;">
                    <a href="{% url 'données:index' %}" style="color: white; text-decoration: none; font-size: 18px;">
                        Se connecter</a></button><br><br>

                <div>
                    <label for="fogot" style="margin: 10px;">Pas de compte?</label>
                    <a href="{% url 'authentification:signup' %}">Cliquer ici</a>
                </div>
               
            </form>
        </div>
       
    </body>
</html>

authentification/templates/authentification/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static '/authentification/css/inscription.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=!">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        
        <div class="form">
            <h2>S'incrire</h2>

            <div class="inputBox">
                <label class="nom">username</label>
                <input type="text" name="username" id="username">
                <small></small>
    
            </div>
            <div class="inputBox">
                <label class=password>Password</label>
                <input type="password" name="pwd" id="pwd">
                <small></small>
    
            </div>
    
            <div class="inputBox">
                <label class="nom">Adresse Mail</label>
                <input type="email" name="mail" id="mail">
                <small></small>
    
            </div>
    
            <div class="selection">
                <label for="poste">Poste occupé(e) : </label>
                <select name="posteoccup" id="">
                    <option value="secret">DGA</option>
                    <option value="secret">Secretaire</option>
                    <option value="secret">Commerciel(e)</option>
                    <option value="secret">Productrice</option>
                    <option value="secret">Informaticien(ne)</option>
                </select>
            </div>
            <br>
            <button type="submit" style="margin-left: 50px ;" > <a href="{% url 'authentification:login' %}" style="color: white; text-decoration: none; font-size: 20px;">S'inscrire</a></button>

        </div>

        
    </form>
</body>
</html>